### PR TITLE
Create NFT details screen

### PR DESCRIPTION
**Pull request by thedevyansh**
This pull request implements the following features:
- [x] Show the image of the NFT in the background and foreground with an overlay.
- [x] Show NFT name, description, and traits associated with the NFT
- [X] Show other NFT details such as creators' addresses, their royalty splits, overview, and summary.

**Screenshots:**

### CODE REVIEW

**Comment by ajamaica** [comment]
I will fix the ci for you

**Comment by thedevyansh** [comment]
> I will fix the ci for you

Hi @ajamaica! Thanks for that. If you want, I can fix this. Seems like github token issue to me.

**Comment by thedevyansh** [comment]
@ajamaica I've made the required changes for fetching NFT trait values. Please review the code. Thanks!

**Comment by Funkatronics** [comment]
Hi @thedevyansh, we need to add a dependency for Flexbox to this PR, no? :
`implementation 'com.google.android.flexbox:flexbox:3.0.0'`

**Comment by ajamaica** [comment]
@[thedevyansh](https://github.com/thedevyansh) I think the ci is failing because the tokens are not on your repo as Marco pointed out. I wont give access to my tokens, but you can add them on your end. We can merge it since its only sample app.

**Comment by ajamaica** [comment]
@[thedevyansh](https://github.com/thedevyansh) Please confirm if we can merge it.

**Comment by thedevyansh** [comment]
@ajamaica I have just committed my GitHub Token with minimum privileges so that the workflow can succeed. Please run the workflow again, and then we can merge it. Thank you!

**Review by ajamaica — CHANGES_REQUESTED** [review]
Remove that token. And delete it from your account NEVER do thatits very insecure.

**Comment by Funkatronics** [comment]
@thedevyansh Apologies for the confusion here. I am new to Github Actions so I am not sure exactly how it handles the secrets when the PR comes form a forked repo. 

From the [Github docs](https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow): 

> Secrets are not passed to the runner when a workflow is triggered from a forked repository.

so we need to figure out how to get around this. I have not found a way yet. 

Alternatively, we could move this code to a local branch within the repo and create a new PR, that should fix it.

**Review by ajamaica — APPROVED** [review]
We run it on local and passed https://github.com/metaplex-foundation/metaplex-android/runs/7222950878?check_suite_focus=true

**Review by Funkatronics — APPROVED** [review]
testing verified in local copy of this branch: https://github.com/metaplex-foundation/metaplex-android/pull/41

**Comment by thedevyansh** [comment]
@Funkatronics @ajamaica Thanks for the workaround. Meanwhile, I’ll explore how to run the workflow successfully by the fork so that it can work the next time.

**Pull request merged**
