### PR TITLE
Fix HTTP Error Handling added in #100

### PR DESCRIPTION
**Pull request by Funkatronics**
## Description
- Fixed up error handling in JdkHttpDriver

## Work Completed
- made a mistake in my previous pr (#100) that was causing fatal errors to still get through, that is now fixed
- added output error handling (fixes fatal error if the http request is bad) 

## API Changes
- none

## Testing
- ran all unit tests, verified that this change does not impact any existing calls or error handling
- confirmed this change works locally by simulating bad requests

### CODE REVIEW

**Comment by Funkatronics** [comment]
Sorry @ajamaica, mad a mistake in my previous PR! 

Big thanks to @creativedrewy for catching this!

**Comment by ajamaica** [comment]
Please rebase

**Comment by Funkatronics** [comment]
Help me obi wan jamacia, you're my only hope 🙏🏽

**Comment by ajamaica** [comment]
The issue is the transfer airdrop the code it's fine. We can merge it

**Review by ajamaica — APPROVED** [review]

**Pull request merged**
